from queries import check_n_value
from queries import get_all_with_x_as_obj
from queries import get_all_with_x_as_subj
from queries import get_articles_for_author
from queries import get_journal_list
from queries import get_label
from queries import get_person_list
from queries import make_academic_article
from queries import make_journal
from queries import make_grant