from owlpost.vivo_utils.connections.pubmed_connect import PUBnnection
from owlpost.vivo_utils.connections.vivo_connect import Connection
from owlpost.vivo_utils.connections.wos_connect import WOSnnection